spring:
  application:
    name: UserManagementProject
#datasource
  datasource:
       driver-class-name: com.mysql.cj.jdbc.Driver
       username: root
       url: jdbc:mysql://localhost:3306/jrtp701db
       password: system
 
  jpa:
      database-platform: org.hibernate.dialect.MySQL8Dialect
      show-sql: true
      hibernate:
       ddl-auto: update
  mail:
    host: smtp.gmail.com
    username: sahoorudrapratap03@gmail.com
    password: fafmvjnqjmgizgwb
    properties:
      mail:
         transport:
           protocol:smtp
      smtp:
        port: 587  
        auth: true
        starttls:
          enable: true  
          required : true   
server:
  port: 4041

mailbody:
  registeruser:
    location:classpath:com/nt/service/user_registration_body.txt
  recoverpwd:
     location : classpath:com/nt/service/recover_pwd_body.txt